name: myapp
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  go_router: ^17.0.1
  json_annotation: ^4.10.0
  freezed_annotation: ^3.1.0
  google_fonts: ^8.0.0
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^3.2.4

flutter:

  uses-material-design: true

  assets:
    - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
